### ISSUE TITLE
GIVgarden harvest box - Liquid amount

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#121]
This is the amount of liquid (claimable) rewards that the user has earned from the GIVgarden unipool rewards contract. They start generating rewards when they wrap their GIV, either on the GIVfarm page (GIVgarden staking pool on xDai) or when they wrap GIV via the gardens UI.

This **does not** include the GIV rewards that are "to be streamed" / (vested)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/5a19adaf-0300-4c42-bd81-a1ca9818de27)

When they click "harvest" they get a popup like this one (but it should say "GIVgarden Rewards" at the top.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/044386a4-f14c-4c5d-abf3-7fd83c1d8fad)

**Comment by laurenluz** [comment]
Note: should go to 0 after harvesting

**Comment by aminlatifi** [comment]
Yes. If I am not mistaken this value 
![image](https://user-images.githubusercontent.com/5684607/143871107-7068920d-dfae-4da5-8cb5-d0585aa280b5.png)
should match this
![image](https://user-images.githubusercontent.com/5684607/143871137-3656c78d-9a44-43a1-9a59-6d11a8e6e1df.png)


Also this section of claimable from GIVBacks
![image](https://user-images.githubusercontent.com/5684607/143871290-83c5ddda-3115-4ed6-aeeb-ffd1416659aa.png)
is the liquid part of GIVBacks. I mean the part will be transferred to the user's wallet immediately on the harvest.

And, claimable from GIVstream 
![image](https://user-images.githubusercontent.com/5684607/143871548-11831ffa-232f-419e-8fd4-57947d950f96.png)
Has the GIVBacks liquid inside since GIVBacks has been paid (allocated on token distro) before.

**Comment by laurenluz** [comment]
> Yes. If I am not mistaken this value
![image](https://user-images.githubusercontent.com/5684607/143871107-7068920d-dfae-4da5-8cb5-d0585aa280b5.png) 
should match this 
![image](https://user-images.githubusercontent.com/5684607/143871137-3656c78d-9a44-43a1-9a59-6d11a8e6e1df.png)

Yes!! except clearly that should say "GIV" not "GIV/WETH"

> Also this section of claimable from GIVBacks ![image](https://user-images.githubusercontent.com/5684607/143871290-83c5ddda-3115-4ed6-aeeb-ffd1416659aa.png) 
is the liquid part of GIVBacks. I mean the part will be transferred to the user's wallet immediately on the harvest.

Yes!! it goes to their wallet whenever the user harvests GIV from anywhere on xDai.

> And, claimable from GIVstream ![image](https://user-images.githubusercontent.com/5684607/143871548-11831ffa-232f-419e-8fd4-57947d950f96.png)
Has the GIVBacks liquid inside since GIVBacks has been paid (allocated on token distro) before.

No actually, for this I think it would be good to show it on the frontend as the `total amount liquid from the GIVstream` minus `liquid amount from GIVbacks`? two distinct values. Then it is clear to the user what they got as a result of donating to verified projects. What do you think @aminlatifi ?
