### ISSUE TITLE
Flow rate on xdai and eth are the same, but I didn't claimed on Koven

### ISSUE THREAD

**Issue by MoeNick** [Giveth/GIVeconomy#208]

**Comment by laurenluz** [comment]
@MoeNick can you add screenshots or more info? for my, my flowrate is different on Kovan & xdai

**Comment by laurenluz** [comment]
the GIVstream progress bar is universal... it applies to *all* the tokens, not just yours. It is showing how much time is remaining for all GIVstreams to flow.

but hearing your confusion, I think we can maybe add tooltips or something to make that more clear.

As for your GIV/week flowrates... on kovan it is 0 because you didn't earn anything, and on xdai you have a flowrate because you earned some rewards. the way it is shown is correct
