### ISSUE TITLE
GIVdrop: Bowen to look into Frame Problem or find an alternative solution

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#21]

**Comment by bowensanders** [comment]
update: mitch and I were able to start some frame tasks using Agent which now require several more people to vote on them to see if they work.

We will also need to revisit whether or not we *actually* have to be able to claim an airdrop from the aragon address or not since anyone can usually claim for a secondary address

**Comment by DonnaOftadeh** [comment]
@bowensanders Guys! What is the update on the Frame, are we still waiting for our test DAO projects to get votes ? we need this to be done till the end of the week latest, please let me know how we can accelerate this, GIVdrop distro data is about to be finished and we need this ASAP!

**Comment by divine-comedian** [comment]
Thanks for the nudge Donna! I cheked up on the Aragon DAO and enacted the votes that did pass. The transactions went through successfully! 

I think Frame will work for the GIVdrop functions that we're intending to do!

**Comment by DonnaOftadeh** [comment]
@divine-comedian so happy to hear that :) so I guess this task is done, and all the related block tasks are unblocked so we can move forward, right?

**Comment by divine-comedian** [comment]
Yes!
