### ISSUE TITLE
Can't see the banner to switch networks... then i clicked the button and nothing happened

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#264]
![Screen Shot 2021-12-14 at 12 03 38 PM](https://user-images.githubusercontent.com/14945613/146054613-5ee81474-a91f-4e46-b3b1-0187166af9f0.png)

The banner to switch to xdai is there but some how I scrolled and it went away (not intending to) so i never saw it... 

But when I click the button.. nothing happens and i think its broken... can we have the banner AND add a pop up?

Assume the user is blinded by greed after looking at those calculators and can't see the banner... we really need a pop up on button click if it's not going to work.

**Comment by laurenluz** [comment]
FYI @pkretzschmar the banner *was* there (it didn't go away)... it was just at the top of his page and hidden because at some point he scrolled down... he didn't notice it at all.

He was connected to the right wallet address (that had tokens to claim) with metamask, but was on the wrong network... so he didn't get the popup saying "connect to the eligible address".

In this case, when the user clicks "claim"... the "switch to xDai" thing should popup in their face and they can click it to switch to the correct network

**Comment by GriffGreen** [comment]
See issue #267 as well... we should have "Connect to the Eligible address show people how to do that.
