### ISSUE TITLE
GIVdrop: When you claim your GIVdrop, there should be a clear tx pending and confirmed flow

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#269]
There should be some pop up that keeps them entertained while they are claiming... ideally it is fun ;-)

**Comment by laurenluz** [comment]
Let's make the claim flow like this... I think @mendesfabio can help w this since he's been fixing this in the app elsewhere

- user clicks claim
- [ ] user sees harvest modal popup #274 
![image](https://user-images.githubusercontent.com/75490971/146272063-72c23940-e896-4ebf-b18c-2d41a9c17a83.png)

- user clicks "havest"
- [ ]  user sees "harvest pending"
![image](https://user-images.githubusercontent.com/75490971/146272091-08d4b978-45e2-4244-a7ab-0663daf9396a.png)
- metamask tx prompt comes up, user accepts
- [ ] user sees tx submitted modal
![image](https://user-images.githubusercontent.com/75490971/146272278-bba724fd-4352-4ec8-83dc-fac6caa12987.png)

- [ ] user sees tx confirmed modal w tx hash link
![image](https://user-images.githubusercontent.com/75490971/146272338-adbfbfca-a1f4-4947-bb7c-1afff6971b54.png)

**Comment by GriffGreen** [comment]
- [x] The final pop up is pretty!

![Screen Shot 2021-12-17 at 11 10 24 AM](https://user-images.githubusercontent.com/14945613/146605782-a2204bef-a3ab-4a4f-b820-09443a6a0509.png)


 - [ ] But the waiting modal isn't. 

![Screen Shot 2021-12-17 at 2 51 06 PM](https://user-images.githubusercontent.com/14945613/146606596-bcd5ccdd-c0c0-450f-8544-ca07520f2bf2.png)

It should look like this:

![Screen Shot 2021-12-17 at 2 55 33 PM](https://user-images.githubusercontent.com/14945613/146607038-1bd9d3e6-42f5-4e22-a97f-a2ce9822f42e.png)

EXCEPT the words should say "Transaction Pending"




- [ ] And neither is the Submitting transaction

![Screen Shot 2021-12-17 at 2 51 17 PM](https://user-images.githubusercontent.com/14945613/146606627-1f9f077f-b19a-4fb4-9a7f-150e614048ec.png)

It should look just like the one in the GIVfarm
![Screen Shot 2021-12-17 at 2 55 33 PM](https://user-images.githubusercontent.com/14945613/146607424-de93e82f-bb8b-4d68-ae0f-c0ba5fa04891.png)

**Comment by GriffGreen** [comment]
Make sure to get those Blockscout links to work ... see issue #334

**Comment by WhyldWanderer** [comment]
I just claimed on Deployment 6 and the waiting modal is still not updated.
![image](https://user-images.githubusercontent.com/74267818/147137574-32d59ff4-07b0-411e-8277-feec0c465e3a.png)

**Comment by laurenluz** [comment]
It's working just fine!

![image](https://user-images.githubusercontent.com/75490971/147291374-9a262687-46ab-4037-a76d-a436355e9982.png)
