### ISSUE TITLE
Harvest modal is a bit long and crazy

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#353]
When there are GIVbacks and all the things, it looks really big and wild:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/8bf1ae64-5fce-46be-958b-7f21d3d9a9e0)

Pedro suggested something like this, but let's decide how to fix it post-launch. @markoprljic could perhaps help us w designs (but after launch!)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/97574652-76d4-4c3d-a592-70d25f6cba0a)

**Comment by markoprljic** [comment]
Yes, this works!

**Comment by laurenluz** [comment]
related to #404

**Comment by GriffGreen** [comment]
Added to your GIVstream flowrate is also confusing.... here is some feedback from @krrisis

![photo_2021-12-27_14-51-57](https://user-images.githubusercontent.com/14945613/147506474-39073226-a764-416d-a186-74df1de51545.jpg)
![photo_2021-12-27_14-52-06](https://user-images.githubusercontent.com/14945613/147506477-6f673e75-438e-404e-b559-124e63bc752a.jpg)
![photo_2021-12-27_14-52-11](https://user-images.githubusercontent.com/14945613/147506478-f12b1c89-3bfc-42ef-8da3-f007ae345549.jpg)
FYI, on the farming, the following got me confused, just sending it so you can make sure it's what it's supposed to be. If it's all correct don't spend any time on writing it down for me, but just for people like me who don't read manuals :) , this is what I noticed: 

1) So first, it says here that 1.3K tokens are claimable already (crazy nice). 

2) Then when I hit the harvest button it says this 1.3K actually gets added to the "givstream flowrate" and that I actually can claim 3.4K, not 1.3K (pretty confusing to me)

3) Extra surprise.... when I click 'harvest' and check I see it's actually indeed claiming BOTH and these are immediately accessible to me (double confused)



![Screen Shot 2021-12-27 at 2 53 23 PM](https://user-images.githubusercontent.com/14945613/147506521-f4f20a78-da47-4e33-b380-ff555e475fc4.png)



![Screen Shot 2021-12-27 at 2 53 39 PM](https://user-images.githubusercontent.com/14945613/147506534-f50e14ac-4919-4ed2-ac2d-2794f7ee62c3.png)


Kris Antwerp Giveth, [12/27/21 1:38 PM]
and I think many people will do this. I would add some more spacing in between there, possibly even put that in a separate box or with a white frame around it, if there's a small text with a question mark below a number I link that small text to that number. :)

Kris Antwerp Giveth, [12/27/21 1:40 PM]
but hey, maybe it's just me, in any case, that givstream logic is a lot to digest for people I think, you give 3 separate calculations under each other and many people don't read manuals - so that tweak might help. 

I had the same thoughts with the airdrop - when it says only 10% available, combined with a per week amount, people might get confused. But now it just all clicked entirely into place. This is awesome. But I was confused.

Kris Antwerp Giveth, [12/27/21 1:41 PM]
apart from me being very confused about this: the entire process is just sooo flawless. beautiful work, congrats to the team ❤️

**Comment by laurenluz** [comment]
I think we need some more design on this one to make it better. I"m thinking...

- we should show the cumulative amount BIG at the very top with the title "Your claimable rewards: 100 GIV" and "Plus adding to your GIVstream flowrate: 5 GIV/week"
- there should be a breakdown below showing where all the numbers are coming from... from GIVbacks, from your GIVstream, from the GIVfarm GIV/ETH pool... it should show liquid amount and the streaming amounts

@markoprljic are you down to work on this one?

**Comment by markoprljic** [comment]
I'm down @laurenluz soonest I get back.

**Comment by markoprljic** [comment]
After reading Kris comments it is clear that we need to make the cumulative amount prominent because the Harvest function collects all rewards across GIVeconomy and we should clearly state this. 
That being said, we would only have ONE Harvest modal for everything instead of different harvest modals as we do now. 
On the other hand, if user is on the GIVbacks page and sees 40.09 GIV to claim from GIVbacks, clicks on Harvest and we show them a different number like 257.9055 GIV incl. breakdown of rewards below, it still might be confusing. 

Anyway, I'll do the new global modal and we can validate this with user testing.

**Comment by markoprljic** [comment]
First pass on this, check it out @laurenluz 
![Image 2022-01-19 at 2 59 37 pm](https://user-images.githubusercontent.com/5704285/150145415-dbd61468-e854-4b0d-9d2a-2758840c39c2.jpg)

**Comment by laurenluz** [comment]
Ok! So I like it a lot in general.. let's tweak it a bit with comms, some suggestions:

- [ ] I think we should get rid of the "switch network" in the top corner. it's confusing I think to switch from within the modal and will be difficult to implement because you won't be able to switch and then start to open a new claim tx for some other part of the GIVeconomy.
- [ ] Make the top box the total liquid rewards, so remove the title "Claimable from GIVstream" title. I think having just the title "Your Rewards" at the very top is fine
- [ ] Next part should say "adding" instead of "added"... the tooltip should say: "Increase your GIVstream flowrate when you harvest liquid rewards!"
- [ ] The message box should say "When you harvest GIV rewards anywhere in the GIVeconomy, all liquid GIV allocated to you is sent to your wallet and your GIVstream flowrate increases." @markoprljic should we add a "read more"? I can break down the way the allocation works in the docs to make it less confusing and we can link to it.
- [ ] Rewards breakdown - I have lots to say, so I'll make bullet points...

Rewards breakdown
- the user wouldn't be claiming from multiple pools at once... we tried to make this possible on xDai but it was too complicated to implement. they will only ever be able to claim from one pool at a time. So make it show only like GIVfarm and then the pool they are claiming from.
- GIVbacks can be the next entry (will only show if they have something to claim)
- there needs to be an entry showing GIVstream "amount"...

I made a sketch for my suggestions for this...
- we show the GIVstream flowrate at the top and have all the other streams add to it... when the user claims they "Get" the totals... a liquid amount and a new GIVstream flowrate
- the GIVbacks streaming amount will have to be in brackets with a tool tip,.. basically this will have *already* been added to the GIVstream flowrate. tooltip should say "Your GIVstream flowrate has been increased by your GIVbacks allocation already"
- there is also a tool tip on "Your new GIVstream flowrate" that says "Your new GIVstream flowrate after you harvest rewards"
- Maybe we highlight or bold this "Get" line? the liquid amount here will be the same as the number at the very top of the page

What do you think @markoprljic ?
![image](https://user-images.githubusercontent.com/75490971/150220244-117aad90-2ea6-4649-bbd4-e4e71a5e24c3.png)

**Comment by laurenluz** [comment]
I showed Griff and he suggested:
- perhaps we take out the header "source / liquid / flowing"
- call it "harvest" instead of "harvest all" (because the user has no other choice
- Make last line "GET" and the numbers BIG

Aaand
- Create an alternative version which is essentially the same as our current version... only with the "cumulartive amount" at the top, and then we compare them

**Comment by markoprljic** [comment]
@laurenluz wasn't sure I understood that in the brackets and I'd definitely avoid it anyway because it's adding more complexity for the user to understand. Tooltips are not always the solution, we should aim to make the UI intuitive and understandable itself. 
If you could describe me the brackets problem a bit more maybe we can find a better solution. 
If it's already in the stream then we might not even need to add it to this breakdown, instead we can maybe nest it under the GIVstream or use the tooltip that is already there to communicate that. 

Below new modal with all revisions.

![Screenshot 2022-01-26 at 16.22.06.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/7f74fcc9-2d29-491c-a642-10ec3ad80e67)

**Comment by laurenluz** [comment]
Yeah so when GIVbacks are distributed, they get added to the token distro right off the bat (unlike rewards earned in the GIVfarn). This means:
- the GIVbacks "amount" is shown as a constant value which is "the amount earned from GIVbacks that was liquid at the time of GIVbacks distribution"
- the GIVbacks "streaming amount" is also a constant value - a flowrate - and this is added *already* to the GIVstream at the time of GIVbacks distribution... the user does not need to "harvest GIVbacks rewards" in order to increase their GIVstream flowrate. This is show in the GIVstream history table at the time of GIVbacks distribution.
- FYI... the portion earned from GIVbacks that gets streamed is forever part of "claimable from your GIVstream"...

This is why I suggested brackets... because if we have the GIVstream amount as 200 GIV/week in this case... and the amount of extra flowrate that they got from GIVbacks is 10 GIV/week... the 10 GIV/week would already be part of 200 GIV/week... after harvesting, they won't get 210 GIV/week.

For the GIVfarm it's different. when the user clicks "harvest" the 30 GIV/week gets adde to the 200 GIV/week and the end result is 230 GIV/week for the GIVstream. Does that make sense?

**Comment by laurenluz** [comment]
Maybe we can have the GIVstream shown as...

190 GIV/week + 10 GIV/week from GIVbacks (or something like this...) in one "data cell"
and then under it we see the extra flowrate from the GIVfarm they get when harvest.
We leave the GIVbacks streaming amount blank... 🤔

**Comment by markoprljic** [comment]
If I understood this correctly then something like this? @laurenluz 

![Screenshot 2022-01-31 at 13.25.37.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/0443c973-1587-4220-a56c-312cc0adb4c8)

**Comment by laurenluz** [comment]
The only thing missing is the GIVbacks liquid portion. That would come as well when they claim.

Only the flowrate is automatically to their givstream

@markoprljic

**Comment by markoprljic** [comment]
I thought so but wanted to hear it from you. Thanks :)

**Comment by markoprljic** [comment]
@laurenluz I'm just not sure why we're separating the GIVbacks liquid and stream? I understand it's because the stream is already added to the stream and the liquid portion is claimable but still... it looks like this is harder to understand as opposed to the original version with just GIVbacks claimable and stream. 

<img width="613" alt="Screenshot 2022-01-31 at 16 30 16" src="https://user-images.githubusercontent.com/5704285/151822215-00910eea-3c9b-4e1b-a52d-a0453116a93e.png">

Maybe this is better version ...
<img width="613" alt="Screenshot 2022-01-31 at 16 35 47" src="https://user-images.githubusercontent.com/5704285/151823194-f36a9967-154f-4225-a4ae-47418b492350.png">

**Comment by laurenluz** [comment]
Version 2 looks great! I'll see if I can get feedback from @krrisis or any other users

**Comment by markoprljic** [comment]
@laurenluz I asked Kris already and his feedback was positive. 
Let me know if this is ready to pass over to devs.

**Comment by markoprljic** [comment]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4808%3A111862

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

just fixed a minor typo but other than that the content looks good and the modal mostly matches the figma spec. one question for @markoprljic 

are these two columns or rows supposed to be left or right aligned? 

![image](https://user-images.githubusercontent.com/67759413/163846409-dcefb4fc-b39d-488a-b0a6-0ac86a85d154.png)
looping in @MohammadPCh

**Comment by markoprljic** [comment]
Right aligned @divine-comedian

**Comment by divine-comedian** [comment]
looks good then! moving to DONE
