### ISSUE TITLE
Update our Etherscan & Blockscout for our token

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#364]
https://etherscan.io/token/0x900db999074d9277c5da2a43f252d74366230da0

Add the logo and all that

**Comment by laurenluz** [comment]
This is the token logo: https://github.com/Giveth/giveth-design-assets/blob/master/02-logos/GIV%20Token/GIVToken_200x200.png

@aminlatifi the contract deployer needs to add these

I think we should do this last minute though to make sure we are doing it for the *right* *final* tokens

**Comment by laurenluz** [comment]
I messaged in the gnosis chain discord blockscout channel to see if anyone knows how to add the logo!

**Comment by laurenluz** [comment]
from here: https://discordapp.com/channels/502416149343109121/502432256011272195/926094343679389717

viktor — 12/30/2021
Blockscout displays token icons from Trustwalet repository. It should appear on Gnosis chain Blockscout instance, once the info of the original token will be added to the public Trustwallet repo for the ETH Mainnet chain.

viktor — 01/05/2022
You should create a PR to trustwallet assets repository. After PR merged, the icon should automatically appear in Blockscout. For instance, this is a PR to add STAKE token logo https://github.com/trustwallet/assets/pull/2055/files

**Comment by laurenluz** [comment]
we may need to give them 1 BNB for them to merge the PR
they've been strict with rules
@willyogo tried once already, will post the issue here and @GriffGreen will follow up

**Comment by willyogo** [comment]
Here is the failed PR attempt: https://github.com/trustwallet/assets/pull/16846 

and their response:
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

We're not at 10k holders yet, but we are well over 20k txs now! Maybe a good time to try again.

btw, you'll see the FOX token icon is attached to that trust wallet  PR too. I tried making the PR two times from their UI and couldn't figure out how to make that not happen; I think it was leftover on my github account from past PRs to update FOX.

Just made a new PR and once again it added FOX Token. Will add a note proactively this time that most of our hodlers are on Gnosis Chain. Maybe everyone go and add a heart to the PR? https://github.com/trustwallet/assets/pull/17826

**Comment by laurenluz** [comment]
This looks right now on etherscan.

But on blockscout... no logo. do they usually have logos? @GriffGreen ?

https://blockscout.com/xdai/mainnet/token/0x4f4F9b8D5B4d0Dc10506e5551B0513B61fD59e75/token-transfers

**Comment by GriffGreen** [comment]
They do: https://blockscout.com/xdai/mainnet/token/0xb7D311E2Eb55F2f68a9440da38e7989210b9A05e/token-transfers
