### ISSUE TITLE
have to approve token spend on every stake on xdai

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#395]
I'm adding tokens to stake in the GIVgarden farm on xdai - 

everytime I try to stake tokens it asks me to approve I approve and then I need to stake - 

is this normal functionality to have to do this everytime? 

![image](https://user-images.githubusercontent.com/67759413/147370729-133e5c7a-0502-4ae5-91dd-5bc79f468759.png)

**Comment by laurenluz** [comment]
yeah it's because "staking" in this pool is actually the same as wrapping tokens in the garden. and you need to approve before you wrap.

it used to say "approve" and then "wrap" but we changed _wrap_ to _stake_ to make it consistent with the other cards (even though it is a different action)

would be good to add this to the givgarden doc, maybe. I'll make an issue in comms

**Comment by laurenluz** [comment]
ohh actually, I just learned FYI, apparently to stake LP tokens you don't need to approve because they have permit. Also on mainnet the token has permit so you don't need to approve.

also 1hive never uses infinite approve you alwasy need to approve before wrapping. so! I was right about things not needing to change in the UI but we coudl still consider communicating this better in our documentation. @divine-comedian
