### ISSUE TITLE
some giveconomy feedback

### ISSUE THREAD

**Issue by krrisis** [Giveth/GIVeconomy#407]
A few points while going thru this again: 

1) 
There seems to be something wrong under the tab givgarden, in the sense that this shows my givfarm rewards here actually. 
Seeing the logic of the rest it should not have a harvest button. 

2) 
I think for both givbacks & givgarden there is supposed to be no harvest button and the giv/week will just be added under the givstream tab, no? 

![image](https://user-images.githubusercontent.com/6533925/147585548-05fd9b58-4577-47a3-a524-79a3f6a806e1.png)

3) 
Extra strangeness here, the harvest tab you see here top right does NOT exist under givfarm, where these rewards are being generated. 

![image](https://user-images.githubusercontent.com/6533925/147584961-e96f02f2-c4ba-46fa-b117-c1aa4fbc00bd.png)

See this second screenshot, no button at the top 

![image](https://user-images.githubusercontent.com/6533925/147585625-648d5fe0-4709-495f-8d59-865f3193ee4e.png)

4) I donated (you can see me under grassroots economy) following the links, however, here no givback rewards or giv/week is showing up, even on refresh. Maybe this gets there after a delay? But also a bit unclear.

![image](https://user-images.githubusercontent.com/6533925/147585875-39743abe-ec40-4ef4-89ae-62cfe0bebf93.png)

cc @GriffGreen @laurenluz

**Comment by laurenluz** [comment]
Hey @krrisis - thanks for the feedback! I can totally understand your confusion.... it is actually working exactly as intended but there is some missing pieces of communication that I'll make issues to fix.

FYI though...

When you stake in the 100% GIV staking pool on xDai it is the same as wrapping tokens in the GIVgarden to vote... in both cases, you get gGIV and you earn rewards. That is why you are thinking those are your GIVfarm rewards masquerading as GIVgarden rewards, when in fact they are the same thing. 

The reason there is no button to harvest at the top of the GIVfarm page is because the rewards shown are cumulative... they are the rewards you're getting from multiple pools added together... if we created a "harvest all" it would result in multiple tx and potentially a lot of gas.

The reason the "adding to your GIVstream" amount shows up at the top of each card is because until you "harvest" rewards... this flowrate is not actually added to your total GIVstream flowrate on giv.giveth.io/givstream - once you "harvest" and the tx goes through... then it shows up

Re: GIVbacks... you need to wait until the 2 week round is over to get your GIVbacks. you can see round info lower (and this explanation) lower on the page.
![image](https://user-images.githubusercontent.com/75490971/147594573-6d584233-d9d4-44a2-8f06-bb68f6d61ae8.png)

Hope that helps to clarify things! I will make some issues to rework the presentation so the flow is less confusing and more clear for users! Appreciate the feedback <3

**Comment by krrisis** [comment]
Hey Lauren,

These clarifications help a lot!
Thx for the extensive feedback on the feedback and happy to hear that it's more a question of adding some more details on what is what than a real issue.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
