### ISSUE TITLE
Frontend fixes to GIVeconomy (GIVdrop and homepage)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#414]
@markoprljic as per your comment in the design channel, you want to add the video to https://giv.giveth.io/

https://www.youtube.com/watch?v=LEw8PaJylNA

Can you give use some design idea as to where to put it?

**Comment by laurenluz** [comment]
love the idea btw

**Comment by markoprljic** [comment]
I made the new header with fullwidth video and moved the sub navigation at the top https://www.figma.com/proto/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?page-id=2%3A60&node-id=3948%3A111086&viewport=380%2C48%2C0.33&scaling=min-zoom&starting-point-node-id=19%3A17139

![Image 2022-01-14 at 4 49 36 pm](https://user-images.githubusercontent.com/5704285/149544365-bbc33864-4b60-4d3e-82d1-c94b74abe544.jpg)

@laurenluz

**Comment by laurenluz** [comment]
Looks awesome! @MoeNick can we add this to cherik for this sprint?

**Comment by MoeNick** [comment]
> Looks awesome! @MoeNick can we add this to cherik for this sprint?

@MohammadPCh would you provide estimations? If it's tiny we can bring it to an unplanned budget.

**Comment by markoprljic** [comment]
- [ ] Move sub navigation at the top
- [ ] Add full-bleed video (no auto playback) overlayed with giv tokens incl a Play button
- [ ] Update GIVdrop box with options to buy giv
- [ ] Add additional boxes below the GIVdrop box

Figma here https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3948%3A111086

**Comment by laurenluz** [comment]
@MoeNick would be nice to have in this sprint, if there's time

**Comment by laurenluz** [comment]
Adding to Marko's comment with links to the original issues & extras:

- [ ] Move sub navigation at the top #443 
- [ ] Add full-bleed video (no auto playback) overlayed with giv tokens incl a Play button
- [ ] Update GIVdrop box with options to buy giv #458 
- [ ] Add additional boxes below the GIVdrop box

**Comment by aminlatifi** [comment]
@laurenluz let's make this an epic and define subtasks 
https://github.com/Giveth/liquidity-mining-dapp/issues/163 has moved tabs to the top

**Comment by MohammadPCh** [comment]
@markoprljic 
At the end of the video, the screen turns black, can we change the end of the video to something else?
![Screenshot from 2022-04-24 13-08-30](https://user-images.githubusercontent.com/17097576/164967992-5709542f-7a0a-4eb1-88c6-3035362a5cf4.png)
I hope to solve it with move the video to the start point. but I think it's better to fade to blue instead of black at the end. (This is my suggestion, I'm not a great designer such you :D )

**Comment by laurenluz** [comment]
also btw it looks AMAZING

**Comment by divine-comedian** [comment]
hey @MohammadPCh  - still missing the buy GIV text on the GIVdrop card 

![image](https://user-images.githubusercontent.com/67759413/165540770-a30591a2-05fe-4621-9a78-60934573dcde.png)

as per - https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3948%3A111086
I belive this link should link to https://app.honeyswap.org/#/swap?outputCurrency=0x4f4F9b8D5B4d0Dc10506e5551B0513B61fD59e75

Also some of the text is off on the buttons for the cards below 
unclear to me otherwise what  
> Add additional boxes below the GIVdrop box

@laurenluz  do you know what this means? staging looks almost identical to the figma.

**Comment by laurenluz** [comment]
the "additional boxes" are referring to the GIVbacks, GIVgarden, GIVfarm cards below the GIVdrop thing in your image. Looks good.

**Comment by MohammadPCh** [comment]
Thank you @divine-comedian ,
I will fix it.
