### ISSUE TITLE
New merkle drop to test Torus wallets

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#429]
As per #405 we had an issue where torus users weren't able to claim their GIVdrop.

Hopefully it's fixed now but we need to test it!

@aminlatifi can you make a new merkle drop w test tokens and include these addresses so we can test claiming the GIVdrop w Torus accounts?

https://docs.google.com/spreadsheets/d/1nJJ8sjcSviST6NVfA6FUHMnZo2QPePh3iP0iBMQzTjM/edit#gid=0

**Comment by aminlatifi** [comment]
@laurenluz By this link you can test torus wallet.
I deployed new merkle distro and also a new backend.
I took long time since torus has issue with setting gas price options!! I fixed the issue and now on develop you can test whether metamask works with correct gas price and a also by torus you should be able to make a tx (before we couldn't )
