### ISSUE TITLE
Refactor subgraph deployment (backend)

### ISSUE THREAD

**Issue by MoeNick** [Giveth/GIVeconomy#615]
Using relation entity subgraph feature for improvement.

**Comment by aminlatifi** [comment]
@mendesfabio Please list any improvement you think can be applied to our subgraph design

**Comment by aminlatifi** [comment]
@mendesfabio I think we can redesign our entities in a way that we don't need to define separate variables per farm and stream in the `balance` entity. We can have one entity for saving stream balance per <user,tokenDistro> touple , and another entity to save farm balance per <user,farm> touple.

**Comment by laurenluz** [comment]
@mendesfabio messaged me last week that he is working on this... and already designed what it will look like. He was concerned because refactoring the subgraph would also require refactoring the frontend... and he doesn't want to delay GIVpower... but we have a lot of frontend bandwidth still, right @MoeNick ?

**Comment by MoeNick** [comment]
@laurenluz under this epic #614  we also have a front-end related issue, so I created this to plan, make it clear and start async with @mendesfabio , so right now it's black-box for us and Im worried we get blocked soon or late, so to facilitate the communication between devs, I asked @mendesfabio to show us a design and we can slit it to doable tasks for further version. Thanks
