### ISSUE TITLE
API for collecting eligible donation data

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#640]
https://github.com/Giveth/givback-calculation/issues/18

<blockquote>
The purpose of this API is to collect donations of certain whitelisted tokens to a certain project on giveth in a given time period and tell us the total sum of token donations for each individual donor to the whitelisted project  and tell us how many NICE tokens we should mint for each donor

it will accept these parameters:

- start date 
- end date
- whitelisted tokens
- projectId
- NICE minting ratio

and it will return 2 CSV files 

the <b>1st</b> with just data needed for distribution: 
distribution:
- donor address
- NICE tokens to receive
- token Symbol (NICE)

the <b>2nd</b> with more complete donation data for review/analysis:
- donor address
- eligible donation date
- eligible donation currency
- eligible donation amount
- projectId
- NICE tokens earned for donation
</blockquote>

**Comment by mohammadranjbarz** [comment]
There are some draft of APIs on staging ENV
https://givback.develop.giveth.io/staging/api-docs/#/NICE

**Comment by divine-comedian** [comment]
testing this out @mohammadranjbarz 

these I think are the parameters we want: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/177316747-c9470faf-5377-4336-aef3-7f53e08b4847.png">

however the output produces an error:
Error: bad request
```
{
  "message": "eligible is not defined"
}
```

**Comment by divine-comedian** [comment]
I also tried `calculate-nice-tokens` with the same parameters and it produced this error;

```
{
  "message": "Data should not be empty or the \"fields\" option should be included"
}
```

**Comment by mohammadranjbarz** [comment]
Thanks @divine-comedian 
I just fixed your reported issues and deployed a newer version on staging and about niceShares being empty maybe in your specified range there is no donation to that projects with sent token, because in this link we have them

https://givback.develop.giveth.io/staging/calculate-nice-token?startDate=2022%2F01%2F14-16%3A00%3A00&endDate=2022%2F01%2F21-15%3A59%3A59&nicePerDollar=0.5&whitelistTokens=GIV%2CETH%2CWETH&projectSlugs=unchain-fund%2Cthe-giveth-community-of-makers%2Cunchain-fund&download=no

<img width="1424" alt="Screen Shot 1401-04-20 at 16 46 01" src="https://user-images.githubusercontent.com/9850545/178262074-d5d4e934-196a-4f8d-9e8f-09a64e785380.png">

**Comment by divine-comedian** [comment]
tested this out and checked the nice eligible donations against the regular givbacks eligible donations, looks to be capturing all the right data!
you can see some of the work I did comparing results here:
https://docs.google.com/spreadsheets/d/1JHdNW45KNf5h1mcf4ZiIMqe-vkl6Q_RwtC0KnT1IStU/edit?usp=sharing

the csv file outputs are working well too! Calling this done!
