### ISSUE TITLE
Call for GIVgarden delegate & forum post

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#687]
The GIVgarden has the option to delegate your voting power to someone.

We never really did an organized call for delegates, so no one is really using this feature.

Aragon recently got a bunch of GIV, staked it, and now want to delegate, but there are no resources for them.. they don't know who they can delegate to even.

I think we should make a forum post asking people to submit their delegation information, and then allow people to post on there... then anyone who wants to delegate their GIVgarden voting power can just read that forum post and add in their address via the GIVgarden.

It's a really simple delegation MVP, and I think its kind of overdue.

**Comment by leuts** [comment]
Hi everyone, Anthony here from Aragon. As Aragon continues to grow in the ecosystem and participate in and with other DAOs/orgs, we want to make sure we make smart decisions when delegating any tokens we hold. Currently it's quite difficult to figure out and build a proposal internally for Aragon to decide on a good delegate match for Giveth. We also don't want to throw the voting power at Griff whom we know very well, simply because we know him. 

Currently from a UI perspective the easiest way to see any delegates is to go on a live vote and the only visible indication of delegates is that top 5 list that comes up in Gardens on the right side of the screen. There we often see a few large delegates we may know, i.e. Griff, Adam. But it basically ends there. 

It would be great if there was a list of individuals who are delegates, or want to be delegated to from Aragon, including information on their ideals, vision, etc. for Giveth. Agree with Lauren's proposal above as an MVP. 

Don't hesitate to message me to get any more info! And thanks :D <3

**Comment by divine-comedian** [comment]
I've assigned myself to this issue. 

I wanted to go through the flow myself on Gardens and I'm having some technical issues with delegation. I'm going to work with 1hive to resolve these issues before writing this forum post.

**Comment by divine-comedian** [comment]
first draft for review!
https://docs.google.com/document/d/1aUiGRRXbhbv_9Aat3EEi11KlQp8DGeE0Vz5v5Htb1v8/edit?usp=sharing

**Comment by laurenluz** [comment]
Fantastic! you're so great!! I love how you made the video too. Thanks Mitch. I left some small comments, and then I think it's good to go.

**Comment by laurenluz** [comment]
@c0ric0ri once this is posted, we should tweet about it. @divine-comedian when you post, please leave a comment here.

**Comment by WhyldWanderer** [comment]
Reviewed! I left some suggestions?

**Comment by leuts** [comment]
From an external standpoint looking good! Happy to help out and review it fully as an external at the very end so feel free to ping :)

**Comment by divine-comedian** [comment]
live!

https://forum.giveth.io/t/open-call-for-givgarden-delegates/772


and vote for meeee!
https://forum.giveth.io/t/mitch-for-givgarden-delegate/773
