### ISSUE TITLE
Budget Box Research for Qualitative Assessments of Projects

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#750]
I am working with some researchers from Colony and @marthendalnunes on a cool project that could be used to create a novel governance method. 

Colony was using it to decide budgets, but i want to use it to rank projects on Giveth.

The idea is that anyone can come on and do pair wise assessments between projects and that this can also influence the rate. 

The current status is that General Magic has funding to build a PoC.

**Comment by chad-fi** [comment]
https://colony.io/budgetbox.pdf

**Comment by GriffGreen** [comment]
https://github.com/kronosapiens/mirror/blob/master/src/modules/power.js

**Comment by Cotabe** [comment]
GM team!

I got a lot of feedback about pairwise voting systems. It's from a user that used a similar model in a game of decorating a room. Voting gave them rewards for buying more stuff and keep decorating the room. 

She (& according to her, most of their community) didn't like the pairwise comparison. I think the reasons are good insights and we should consider them for Budget box. 

1. Most people voted for the first project. There was a reward for voting, so many people voted for whichever came first to get the rewards. If the position is randomized this shouldn't affect budget box.

2. Sometimes they got two options that were amazing and sometimes they got 2 options that were terrible. This frustrated them. I see 2 ways to mitigate this frustration: a) have 1 or 2 bonus for when both projects are awesome and 1 or 2 "none vote" option. b) Instead of a binary vote, have the chance to distribute 3 or 5 votes between the 2 projects. 

In general, she suggested ordering 5 projects instead of pairwise comparisons. I don't necessarily agree, I like ordering projects, but also the simplicity of pairwise comparison, just passing the feedback.

**Comment by Cotabe** [comment]
Here is a bit of my feedback:

1. It would be great to have a blurb about each project in a nutshell so that the core idea is fully readable in the UI.

2. It's not only about the projects/idea, but also about the implementation. It would be good to have in the app, the latest milestones achieved and maybe how would the next funds would be used in a short blurb too.
