### ISSUE TITLE
Grant application to Polygon

### ISSUE THREAD

**Issue by Cotabe** [Giveth/GIVeconomy#760]

**Comment by SnakeGH** [comment]
- What would be the main ask?
    - Ask for 50-100K to add a chain and sell to pay salaries, or...
    - 300-500K to create an LP against the GIV token

What the migration to polygon proposal would like on the Giveth Dev end? 
    - liquidity pool with MATIC to allow GIV to have a secondary market on polygon
    - Rough Estimation for migration on Dev side for below actions is 1.5 months (1 FE fulltime, 1 BE fulltime with a Tester 50%, designer 10% & a PM 70% FT)
        - Front End
            - add new networks to the multi-recipient addresses section in creating a project page and verification flow
            - add new networks to web3-react config
            - add new networks to the donations table in the project page
            - add new networks config to the configuration file
            - find a way to fetch new tokens prices in new networks
            - supported networks modal on the donation page
        - Product
            - revise switch network user flow (design included)
        - Back End
            - rewrite donation verification with network

**Comment by spectoregia** [comment]
Got an update from Polygon on 23.12: 

Dear Village Community,

Earlier this week, it was announced Polygon DAO will wind down and that elements of the DAO would be added into Polygon Village: https://polygon.technology/blog/community-update

To provide more effective support to projects, we will temporarily suspend the Voucher Program for a few weeks and may reintroduce it with new features and greater efficiency in the new year.

The results of previous rounds of grants and vouchers will be communicated directly to the awarded projects in the coming weeks.
--------------------------

What does this mean? 

The community is still reviewing and informing the teams that submitted applications in November/December (that is us). I have been told they will most probably get in touch but they will need more time.

otherwise, they are launching a new program called "vouchers" to support the next 10k projects building on Polygon. New applications will be accepted in 2023.
