### ISSUE TITLE
Ethereum Foundation ESP

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#776]
Ethereum Foundation: 

Twitter: https://twitter.com/EF_ESP
Website: https://esp.ethereum.foundation/
ETH foundation grants update: https://blog.ethereum.org/2018/10/15/ethereum-foundation-grants-update-wave-4

Now accepting Grant applications for Wave V
https://blog.ethereum.org/2018/10/15/ethereum-foundation-grants-update-wave-4

FYI
https://blog.ethereum.org/2018/10/24/how-the-ethereum-foundation-grants-program-makes-decisions

**Comment by SnakeGH** [comment]
After some research on ETH grants, here is the basic overview of the two types they have…

Project Grants 
•    More than $30K but usually less than $250K 
•    decision in two months, typically 
•    more complex and larger in scope projects 
•    already have a mature idea 

Small Grants (or DEV grants)
•    Usually around $10K but up to $30K cap 
•    Quicker decisions on approval 
•    In early stages or experimental development 

So, we need to decide on what are we trying to do with an ETH grant here? Add it to our chain? Or do we want money for development? Because if it's just adding a new chain, I think we won't really need more than $25k realistically, and therefore maybe we pump it up to around $50K…but I don’t think they will give us more than $10k or max $25k for this type of DEVgrant. 

Another idea, which comes from our brilliant Yass, maybe we can think of proposing GIVfi or even GURVES projects and get funding for research and development on these projects...which then we might see the grant go all the way up to $250K

Also, something to keep in mind, which comes directly from their website: "while exceptions can be made in certain cases, ÐΞVgrants range from $1,000 to $10,000 per project, or just enough to cover a few months of living expenses for one or more developers." And… "It is NOT a ÐApp seed funding program. At this point in our development process, most ÐApps score near the bottom of critical value for our development process."

Lastly, after cross referencing with Kurt / MoeNick...they believe that fundamentally it is technically possible to bridge GIV & ETC...but they thought ETC was nearly a dead chain and if the future of Giveth is multichain, which we all believe it is, if Giveth does move forward with a solution like tokenbridge, connext or something else, it would be easy to reproduce for other chains. Kurt is going to look more into it though, because he doesn't know anyone using ETC :)

**Comment by divine-comedian** [comment]
# GIveconomy research notes
Multichain ... anybridge - rebranded after a hack - they had ETC classic as an option - it's mostly a deadchain but the ETC spends well and people could donate ETC to a giveth project

needs to figure out how to add a token to this bridge @GriffGreen to add link to bridge

**Comment by SnakeGH** [comment]
@GriffGreen reached out to an internal ETC steward for some more insight. More info to come

**Comment by SnakeGH** [comment]
Internal ETC steward said to put this on the shelve for now, as ETC is not ready to receive applications for grants and therefore, approve or offer

**Comment by spectoregia** [comment]
I have decided to revisit this and apply for a "general" grant. The draft can be found here:
https://docs.google.com/document/d/1ZGIiFSiZt_r2I5Z0sL_D8VeO6H7UWD3FklFzoHDFYI4/edit
(currently awaiting Griff's feedback)

I think the confusion arose when we confused eth foundation grant with ETC and decided not to proceed. This one is ETH and we can simply ask them to support our project overall based on the information on their web.
