### ISSUE TITLE
Chainlink Social Impact Grant

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#784]
**Social impact grants**
Social impact grants support nonprofits and organizations that are exploring how to use smart contracts and on-chain data to benefit emerging markets and contribute to the betterment of humanity.

Apply here: https://chain.link/community/grants#apply-for-a-grant

**Comment by spectoregia** [comment]
hey @tropicalmangos - thanks for implementing my suggestions there - I don't have anything more to add. just one question - the part we state our ask with the amount comes later in the grant process or shall we include it somewhere in this grant? Do you have the estimation on the dev work for this?

**Comment by spectoregia** [comment]
yea sure, I would vote to go ahead with it if Griff has OKed the proposal.

**Comment by MoeNick** [comment]
Sorry to respond late, @tropicalmangos 
Their price services can integrate into our DAPP but it is designed to use for smart contracts and it does not add much value to our web-application, due to the cost of their subscription I doubt it can be a good solution for us from product's perspective. 
However, for other areas of cooperation, I don't have any clear clue how we can go forward, maybe other product managers can follow it up better than I do.
